---
title: "More_Mapping"
author: "Jenna Moscaritolo & Jung Hwa Yeom"
date: "11/11/2020"
output: pdf_document
---

```{r setup, include = FALSE, warning = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse","drat","maps","tmap","sf","viridis","sp","hurricaneexposuredata","hurricaneexposure","tmaptools")
```

## 1. Data Cleaning

```{r}
# Extracting general data for mapping
addRepo("geanders")
data("hurr_tracks")
data("rain")
```

```{r}
# Pulling map data
ob <- st_as_sf(map('county',plot=FALSE,fill=TRUE))
colnames(county.fips)[2] = 'ID'
ob <- merge(ob, county.fips, by="ID")
```

```{r}
# Filtering target hurr_tracks data
dt_o <- hurr_tracks %>% filter(storm_id == "One-2009")
dt_e <- hurr_tracks %>% filter(storm_id == "Earl-2010")
dt_i <- hurr_tracks %>% filter(storm_id == "Irene-2011")
```

```{r}
# Filtering target rain data
ra_o <- rain %>% filter(storm_id == "One-2009") %>% group_by(fips) %>%
  summarise('storm_id'=storm_id[1],'precip'=sum(precip))

ra_e <- rain %>% filter(storm_id == "Earl-2010") %>% group_by(fips) %>%
  summarise('storm_id'=storm_id[1],'precip'=sum(precip))

ra_i <- rain %>% filter(storm_id == "Irene-2011") %>% group_by(fips) %>%
  summarise('storm_id'=storm_id[1],'precip'=sum(precip))
```

```{r}
# Changing fips to numerics
ra_o$fips <- as.numeric(ra_o$fips)
ra_e$fips <- as.numeric(ra_e$fips)
ra_i$fips <- as.numeric(ra_i$fips)
```

```{r}
# Merging data by fips variable
ra_o <- merge(ob, ra_o, by="fips")
ra_e <- merge(ob, ra_e, by="fips")
ra_i <- merge(ob, ra_i, by="fips")
```

```{r}
# Pulling the coordinates for each hurricane path
One <- cbind(dt_o$longitude,dt_o$latitude)%>%
  Line()%>%Lines(ID='One-2009')%>%
  list()%>%SpatialLines()

Earl <- cbind(dt_e$longitude,dt_e$latitude)%>%
  Line()%>%Lines(ID='Earl-2010')%>%
  list()%>%SpatialLines()

Irene <- cbind(dt_i$longitude,dt_i$latitude)%>%
  Line()%>%Lines(ID='Irene-2011')%>%
  list()%>%SpatialLines()
```

```{r}
# Organize map data
ra_o <- rain %>% filter(storm_id == "One-2009") %>% group_by(fips) %>%
  summarise(storm_id=storm_id[1],precip=sum(precip))
ra.new.o <- as.data.frame(ra_o)
ra.new.o$fips <- as.numeric(ra.new.o$fips)

ra_e <- rain %>% filter(storm_id == "Earl-2010") %>% group_by(fips) %>%
  summarise(storm_id=storm_id[1],precip=sum(precip))
ra.new.e <- as.data.frame(ra_e)
ra.new.e$fips <- as.numeric(ra.new.e$fips)

ra_i <- rain %>% filter(storm_id == "Irene-2011") %>% group_by(fips) %>%
  summarise(storm_id=storm_id[1],precip=sum(precip))
ra.new.i <- as.data.frame(ra_i)
ra.new.i$fips <- as.numeric(ra.new.i$fips)
```

```{r}
# Merging data by fips variable
ra.new.o <- merge(ob, ra.new.o, by="fips")
ra.new.e <- merge(ob, ra.new.e, by="fips")
ra.new.i <- merge(ob, ra.new.i, by="fips")
```


# Plotting the maps

```{r}
# Plotting all three hurricane tracks and amount of rainfall
t_F_o = tm_shape(ra.new.o)+
  tm_polygons(col='precip',title="Rainfall (mm)")+
  tm_legend(position=c("right","bottom"))+
  tm_shape(One)+
  tm_lines(col='red')+
  tm_layout(main.title='One-2009',main.title.position = "center") 
t_F_o

t_F_e = tm_shape(ra.new.e)+
  tm_polygons(col='precip',title="Rainfall (mm)")+
  tm_legend(position=c("right","bottom"))+
  tm_shape(Earl)+
  tm_lines(col='red')+
  tm_layout(main.title='Earl-2010',main.title.position = "center") 
t_F_e

t_F_i = tm_shape(ra.new.i)+
  tm_polygons(col='precip',title="Rainfall (mm)")+
  tm_legend(position=c("right","bottom"))+
  tm_shape(Irene)+
  tm_lines(col='red')+
  tm_layout(main.title='Irene-2011',main.title.position = "center") 
t_F_i
```


